language: sh
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - build-essential
env:
  - USING_ZSH_VERSION="zsh-5.3.1"
cache:
  directories:
    - ${HOME}/zsh
before_install:
  - bash .travis_build_zsh.sh
  - export PATH="${HOME}/zsh/bin:${PATH}"
script: cd tests; zsh --version; zsh ./run_all_tests.zsh
