language: sh
sudo: false
dist: xenial
env:
  - ZSH_FILE="zsh-5.2.tar.gz"
  - ZSH_FILE="zsh-5.3.1.tar.gz"
  - ZSH_FILE="zsh-5.4.2.tar.gz"
  - ZSH_FILE="zsh-5.5.1.tar.gz"
  - ZSH_FILE="zsh-5.6.2.tar.xz"
  - ZSH_FILE="zsh-5.7.1.tar.xz"
before_install:
  - sudo apt-get install -y bsdtar
  - cd "${HOME}"
  - curl -L "https://downloads.sourceforge.net/zsh/${ZSH_FILE}" | bsdtar xf -
  - cd "${ZSH_FILE%.*.*}"
  - ./configure --prefix="${HOME}/zsh"
  - make -j2
  - make install
  - export PATH="${HOME}/zsh/bin:${PATH}"
  - cd "${TRAVIS_BUILD_DIR}"
script: cd tests; make
